spring:
    mail:
        host: smtp.gmail.com
        password: Tjq8old9j
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    connectiontimeout: 5000
                    starttls:
                        enable: true
                    timeout: 5000
                    writetimeout: 5000
        username: pawel4post@gmail.com
    datasource:
        url: jdbc:postgresql://localhost:5432/rest_island
        driverClassName: org.postgresql.Driver
        username: postgres
        password: postgres
    jpa:
        show-sql: true
        database-platform=org: hibernate.dialect.PostgreSQL9Dialect
        properties:
            hibernate:
                ddl-auto: none
                dialect: org.hibernate.dialect.PostgreSQL9Dialect
    liquibase:
      change-log: classpath:db/liquibase/master.xml